main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#papers
    weight: 11
  - name: News
    url: /#news
    weight: 13
  - name: Pre College RL Course
    url: /rl-course/
    weight: 14
